### ISSUE TITLE
Question: LibTiff

### ISSUE THREAD

**Issue by alexbejann** [atetlaw/projios#1]
Hi @atetlaw, 

I was wondering if you have enabled the tiff support for your proj implementation. If not, do you have a suggestion how to do it and include it into the framework that you created?

**Comment by alexbejann** [comment]
I am closing this issue as I solved this problem by using the [PROJ](https://github.com/alexbejann/PROJ) and [libtiff](https://github.com/alexbejann/libtiff) pods.

**Comment by atetlaw** [comment]
Sorry @alexbejann , I haven't paid any attention to this repo in quite a while!

**Comment by alexbejann** [comment]
No worries, thanks for answering!
